./configure --with-features=huge \
--enable-multibyte \
--enable-rubyinterp=yes \
--enable-pythoninterp=yes \
--with-python-config-dir=/lib64/python2.7/config \
--enable-perlinterp=yes \
--enable-luainterp=yes \
--enable-gui=gtk2 \
--enable-gnome-check \
--enable-gtk3-check \
--enable-cscope \
--enable-fontset \
--enable-autoservername \
--enable-cscope \
--enable-largefile \
--enable-fail-if-missing \
--prefix=/usr/local
