# --- Schriftart & Grundeinstellungen ---
font_family      Hack Nerd Font Propo
font_size        14.0
scrollback_lines 10000
allow_remote_control yes

# --- Layouts ---
enabled_layouts splits, grid, stack

# --- Farben (Monokai-Stil) ---
background            #272822
foreground            #d0d0d0
selection_background  #49483e
selection_foreground  #f8f8f2

color0 #272822
color1 #f92672
color2 #a6e22e
color3 #f4bf75
color4 #66d9ef
color5 #ae81ff
color6 #a1efe4
color7 #f8f8f2

# --- Maus & Kopieren/Einfügen ---
# Rechtsklick fügt den kopierten Text sofort ein
mouse_map right press ungrabbed paste_from_clipboard

# --- Tastaturkürzel ---
# Horizontal split (Neues Fenster UNTEN dranhängen)
map ctrl+shift+o launch --location=hsplit

# Vertikal split (Neues Fenster RECHTS dranhängen)
map ctrl+shift+e launch --location=vsplit

# Fenster im Grid anordnen (Standard-Neufenster)
map ctrl+shift+enter new_window

# Zwischen Fenstern mit den Pfeiltasten wechseln
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down

# Broadcast-Fenster unten mit max. 5 Zeilen Höhe öffnen
map alt+a launch --location=hsplit --bias=15 --allow-remote-control kitty +kitten broadcast
