
plugins=(
  ansible
  git
  zsh-autosuggestions
  docker
  asdf
  pip
  zsh-autosuggestions
  zsh-completions
  zsh-history-substring-search
  zsh-syntax-highlighting
)


ssh() {
    if [ "$(ps -p $(ps -p $$ -o ppid=) -o comm=)" = "tmux" ]; then
            tmux rename-window "$*"
            command ssh "$@"
            tmux set-window-option automatic-rename "on" 1>/dev/null
    else
            command ssh "$@"
   fi
}

bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line

# User specific environment
PATH="$HOME/.local/bin:$HOME/go/bin:$HOME/bin:$PATH"
export PATH

# export https_proxy=http://192.168.110.10:3128
# export http_proxy=http://192.168.110.10:3128
# export no_proxy="192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,.domain.local,127.0.0.1,localhost"

# gsettings set org.gnome.system.proxy mode 'auto'
# gsettings set org.gnome.system.proxy autoconfig-url 'http://192.168.110.10/wpad.dat'

#export PYTHONWARNINGS=ignore::UserWarning

# export SSH_KEY_PATH="~/.ssh/id_ed25519"

#export VAGRANT_DEFAULT_PROVIDER=virtualbox

#alias df='df -x"squashfs"'

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'

export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

command -v lsd > /dev/null && alias ls='lsd --group-dirs first'
command -v lsd > /dev/null && alias tree='lsd --tree'

source /home/steffen/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /home/steffen/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

unsetopt HIST_VERIFY

